class AppStrings {
  static const Map<String, Map<String, String>> values = {
    'ko': {
      'app_title': '플래너 데스크탑',
      'home': '홈',
      'weekly': '주간',
      'checklist': '체크리스트',
      'settings': '설정',
      'language': '언어',
      'theme': '테마',
      'timezone': '시간대',
      'timezone_hint': '실시간 시계와 오늘 날짜 기준에 사용할 시간대를 선택하세요',
      'current_time': '현재 시간',
      'korean': '한국어',
      'english': '영어',
      'light': '라이트',
      'dark': '다크',
      'system': '시스템',
      'schedule': '일정',
      'memo': '메모',
      'calendar': '달력',
      'day_detail': '일간 일정',
      'weekly_schedule': '주간 일정',
      'global_checklist': '전체 체크리스트',
      'prev': '이전',
      'next': '다음',
      'add': '추가',
      'delete': '삭제',
      'title': '제목',
      'start_time': '시작',
      'end_time': '종료',
      'pick_color': '색상',
      'no_schedule_items': '일정이 없습니다',
      'no_checklist_items': '체크리스트가 없습니다',
      'no_recurring_tasks': '반복 체크리스트가 없습니다',
      'no_weekly_items': '해당 요일 일정이 없습니다',
      'select_language': '언어를 선택하세요',
      'select_theme': '테마를 선택하세요',
      'month_picker': '월 / 연도 선택',
      'cancel': '취소',
      'apply': '적용',
      'checklist_item': '체크리스트 항목',
      'memo_hint': '메모를 입력하세요...',
      'add_recurring_task': '반복 할 일 추가',
      'select_date': '날짜 선택',
      'items_more': '더',
      'sun_short': '일',
      'mon_short': '월',
      'tue_short': '화',
      'wed_short': '수',
      'thu_short': '목',
      'fri_short': '금',
      'sat_short': '토',
      'sunday': '일요일',
      'monday': '월요일',
      'tuesday': '화요일',
      'wednesday': '수요일',
      'thursday': '목요일',
      'friday': '금요일',
      'saturday': '토요일',
      'select_start_time': '시작 시간 선택',
      'select_end_time': '종료 시간 선택',
      'time_required': '시작/종료 시간을 선택하세요',
      'invalid_time_range': '종료 시간이 시작 시간보다 늦어야 합니다',
      'today_live_clock': '오늘 실시간 시계',
      'day_timetable': '하루 시간표',
      'current_task': '지금 해야 하는 일정',
      'next_task': '다음 일정',
      'no_active_task': '현재 진행 중인 일정 없음',
      'no_remaining_tasks': '남은 일정이 없습니다',
      'schedule_visual_hint': '선택한 날짜의 일정을 원형 시간표로 표시합니다.',
      'hour': '시',
      'minute': '분',
      'select_time': '시간 선택',
      'open_month_picker': '월 / 연도 선택',
      'today': '오늘',
    },
    'en': {
      'app_title': 'Planner Desktop',
      'home': 'Home',
      'weekly': 'Weekly',
      'checklist': 'Checklist',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'timezone': 'Time Zone',
      'timezone_hint': 'Choose the timezone used for the live clock and today marker',
      'current_time': 'Current Time',
      'korean': 'Korean',
      'english': 'English',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'schedule': 'Schedule',
      'memo': 'Memo',
      'calendar': 'Calendar',
      'day_detail': 'Daily Plan',
      'weekly_schedule': 'Weekly Schedule',
      'global_checklist': 'Global Checklist',
      'prev': 'Prev',
      'next': 'Next',
      'add': 'Add',
      'delete': 'Delete',
      'title': 'Title',
      'start_time': 'Start',
      'end_time': 'End',
      'pick_color': 'Color',
      'no_schedule_items': 'No schedule items',
      'no_checklist_items': 'No checklist items',
      'no_recurring_tasks': 'No recurring tasks',
      'no_weekly_items': 'No weekly items for this day',
      'select_language': 'Select language',
      'select_theme': 'Select theme',
      'month_picker': 'Select Month / Year',
      'cancel': 'Cancel',
      'apply': 'Apply',
      'checklist_item': 'Checklist item',
      'memo_hint': 'Write memo here...',
      'add_recurring_task': 'Add recurring task',
      'select_date': 'Select date',
      'items_more': 'more',
      'sun_short': 'Sun',
      'mon_short': 'Mon',
      'tue_short': 'Tue',
      'wed_short': 'Wed',
      'thu_short': 'Thu',
      'fri_short': 'Fri',
      'sat_short': 'Sat',
      'sunday': 'Sunday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'select_start_time': 'Select start time',
      'select_end_time': 'Select end time',
      'time_required': 'Please select start/end time',
      'invalid_time_range': 'End time must be later than start time',
      'today_live_clock': 'Today Live Clock',
      'day_timetable': 'Day Timetable',
      'current_task': 'Current task',
      'next_task': 'Next task',
      'no_active_task': 'No active task right now',
      'no_remaining_tasks': 'No remaining tasks',
      'schedule_visual_hint': 'The selected day schedule is shown as a circular timetable.',
      'hour': 'Hour',
      'minute': 'Minute',
      'select_time': 'Select time',
      'open_month_picker': 'Pick month / year',
      'today': 'Today',
    },
  };

  static String text(String lang, String key) {
    return values[lang]?[key] ?? key;
  }

  static List<String> weekNames(String lang) {
    return [
      text(lang, 'sun_short'),
      text(lang, 'mon_short'),
      text(lang, 'tue_short'),
      text(lang, 'wed_short'),
      text(lang, 'thu_short'),
      text(lang, 'fri_short'),
      text(lang, 'sat_short'),
    ];
  }

  static List<MapEntry<String, String>> weekDayEntries(String lang) {
    return [
      MapEntry('Sun', text(lang, 'sunday')),
      MapEntry('Mon', text(lang, 'monday')),
      MapEntry('Tue', text(lang, 'tuesday')),
      MapEntry('Wed', text(lang, 'wednesday')),
      MapEntry('Thu', text(lang, 'thursday')),
      MapEntry('Fri', text(lang, 'friday')),
      MapEntry('Sat', text(lang, 'saturday')),
    ];
  }
}
